#!/usr/bin/env python

# Base for CLI
import click

# Tool base class
from tools.base import Base

# Tools
from tools.shs_classification.shs_mapper import SHSMapper as SHSMapper

################
# Main Command #
################

@click.group()
@click.argument('tensor_path', type=click.Path(exists=True))
@click.argument('mask_path', type=click.Path(exists=True))
@click.option('--output_path', default='')
@click.pass_context
def dti_tools(cxt, tensor_path, mask_path, output_path):
    """Diffusion Tensor Image processing tools.

       version 0.0.1.alpha1


       Copyright 2014 Rafael Reggiani Manzo <rr.manzo@gmail.com>"""

    cxt.obj = Base(tensor_path, mask_path, output_path)

#########
# Tools #
#########

@dti_tools.command()
@click.argument('acquisition_directions_file', type=click.Path(exists=True))
@click.argument('significance_level')
@click.pass_obj
def shs_classification(base, acquisition_directions_file, significance_level):
    mapper = SHSMapper(base.tensor_path, base.mask_path, acquisition_directions_file, significance_level, base.output_path)
    mapper.run()
    mapper.save()

if __name__ == '__main__':
    dti_tools()